[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


  [build]
  environment = {
    REACT_APP_FIREBASE_API_KEY = "AIzaSyAnjLzizMl2jy8vT_yaESWthpdhSOkaXfY",
    REACT_APP_FIREBASE_AUTH_DOMAIN = "greydive-test.firebaseapp.com",
    REACT_APP_FIREBASE_PROJECT_ID = "greydive-test",
    REACT_APP_FIREBASE_STORAGE_BUCKET = "greydive-test.appspot.com",
    REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "333108600801",
    REACT_APP_FIREBASE_APP_ID = "1:333108600801:web:7558c5b6675c73762dbca0"
  }